import { Link, useParams } from "react-router-dom";
import { Boton, BotonEnlace } from "../../shared/components/Boton";
import { CabeceraPagina } from "../../shared/components/CabeceraPagina";
import { EstadoVacio } from "../../shared/components/EstadoVacio";
import { Etiqueta } from "../../shared/components/Etiqueta";
import { ListaDatos } from "../../shared/components/ListaDatos";
import { Tarjeta, TarjetaCabecera, TarjetaCuerpo } from "../../shared/components/Tarjeta";
import { ESTADO_CLIENTE } from "../../shared/data/formato";
import { Seo } from "../../shared/seo/Seo";
import pantalla from "../../shared/styles/pantalla.module.css";
import { LineaDeActividades } from "../actividades/LineaDeActividades";
import { useActividades } from "../actividades/apiActividades";
import { useOrigenes } from "../catalogos/apiCatalogos";
import { useOportunidades } from "../oportunidades/apiOportunidades";
import { useContacto } from "./apiContactos";
export function PaginaContactoDetalle(){const id=Number(useParams().id);const valido=Number.isSafeInteger(id)&&id>0;const consulta=useContacto(valido?id:undefined);const oportunidades=useOportunidades(0,{contactId:String(id)});const actividades=useActividades({tipo:"contacts",id});const origenes=useOrigenes();if(!valido||consulta.isError)return <EstadoVacio icono="contactos" titulo="No encontramos ese contacto" descripcion={consulta.error?.message??"El enlace no es válido."} accion={<BotonEnlace a="/app/contactos" variante="secundario">Volver</BotonEnlace>}/>;if(consulta.isPending)return <EstadoVacio icono="contactos" titulo="Cargando contacto…" descripcion="Consultando su historial comercial."/>;const c=consulta.data;const estado=ESTADO_CLIENTE[c.status??"POTENCIAL"];return <><Seo titulo={`${c.firstName} ${c.lastName}`} descripcion="" noIndexar/><CabeceraPagina migas={[{texto:"Contactos",a:"/app/contactos"},{texto:`${c.firstName} ${c.lastName}`}]} titulo={`${c.firstName} ${c.lastName}`} descripcion={c.position} meta={<Etiqueta tono={estado.tono} punto tamano="sm">{estado.texto}</Etiqueta>} acciones={<><BotonEnlace a={`/app/contactos/${c.id}/editar`} variante="secundario" icono="lapiz">Editar</BotonEnlace><BotonEnlace a={`/app/oportunidades/nueva?contactoId=${c.id}`} icono="mas">Nueva oportunidad</BotonEnlace></>}/><div className={pantalla.grillaDetalle}><div className={pantalla.pila}><Tarjeta><TarjetaCabecera titulo="Datos del contacto"/><TarjetaCuerpo><ListaDatos datos={[{etiqueta:"Documento",valor:c.document||"—"},{etiqueta:"Cargo",valor:c.position||"—"},{etiqueta:"Empresa",valor:c.company?<Link to={`/app/empresas/${c.company.id}`}>{c.company.businessName}</Link>:"Cliente individual"},{etiqueta:"Correo",valor:c.email?<a href={`mailto:${c.email}`}>{c.email}</a>:"—"},{etiqueta:"Teléfono",valor:c.phone||"—"},{etiqueta:"Origen",valor:origenes.data?.find(o=>o.id===c.originId)?.name||"—"},{etiqueta:"Observaciones",valor:c.notes||"—",ancho:true}]}/></TarjetaCuerpo></Tarjeta><Tarjeta><TarjetaCabecera titulo="Actividades"/><TarjetaCuerpo><LineaDeActividades actividades={actividades.data?.content??[]} cargando={actividades.isPending} error={actividades.isError?actividades.error.message:undefined} alReintentar={()=>actividades.refetch()}/></TarjetaCuerpo></Tarjeta></div><aside className={pantalla.pila}><Tarjeta><TarjetaCabecera titulo="Resumen" nivel={3}/><TarjetaCuerpo><ListaDatos columnas={1} datos={[{etiqueta:"Oportunidades visibles",valor:oportunidades.data?.totalElements??0},{etiqueta:"Responsable",valor:`Usuario #${c.salesRepId??"—"}`}]}/>{oportunidades.isError&&<Boton variante="secundario" onClick={()=>oportunidades.refetch()}>Reintentar</Boton>}</TarjetaCuerpo></Tarjeta></aside></div></>}
