import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { components } from "../../shared/api/esquema-api";
import { solicitarApi } from "../../shared/api/clienteApi";
export type Oportunidad = components["schemas"]["OpportunityResponse"];
export type OportunidadDetalle = components["schemas"]["OpportunityDetailResponse"];
export type SolicitudCrearOportunidad = components["schemas"]["CreateOpportunityRequest"];
export type SolicitudEditarOportunidad = components["schemas"]["UpdateOpportunityRequest"];
export type PaginaOportunidades = components["schemas"]["PageResponseOpportunityResponse"];
export type Embudo = components["schemas"]["OpportunityBoardResponse"];
export type HistorialEtapa = components["schemas"]["StageHistoryResponse"];
export type FiltrosOportunidades = { q?: string; status?: string; stageId?: string; originId?: string; salesRepId?: string; venueId?: string; companyId?: string; contactId?: string; eventFrom?: string; eventTo?: string };
export const clavesOportunidades = { todas: ["oportunidades"] as const, lista: (p: number, f: FiltrosOportunidades) => ["oportunidades", "lista", p, f] as const, detalle: (id: number) => ["oportunidades", "detalle", id] as const, embudo: (f: FiltrosOportunidades) => ["oportunidades", "embudo", f] as const, historial: (id: number) => ["oportunidades", "historial", id] as const };
const query = (f: FiltrosOportunidades, pagina?: number) => { const p = new URLSearchParams(); if (pagina !== undefined) { p.set("page", String(pagina)); p.set("size", "20"); p.set("sort", "eventStart,desc"); } Object.entries(f).forEach(([k,v]) => { if (!v) return; if (k === "eventFrom") p.set(k, `${v}T00:00:00-03:00`); else if (k === "eventTo") p.set(k, `${v}T23:59:59-03:00`); else p.set(k,v); }); return p; };
export const useOportunidades = (pagina=0, filtros: FiltrosOportunidades={}) => useQuery({ queryKey: clavesOportunidades.lista(pagina,filtros), queryFn: ({signal}) => solicitarApi<PaginaOportunidades>(`/opportunities?${query(filtros,pagina)}`,{signal}) });
export const useOportunidad = (id?: number) => useQuery({ queryKey: clavesOportunidades.detalle(id??0), queryFn: ({signal}) => solicitarApi<OportunidadDetalle>(`/opportunities/${id}`,{signal}), enabled:id!==undefined });
export const useEmbudo = (filtros: FiltrosOportunidades={}) => useQuery({ queryKey: clavesOportunidades.embudo(filtros), queryFn: ({signal}) => solicitarApi<Embudo>(`/opportunities/board?${query(filtros)}`,{signal}) });
export const useHistorialEtapas = (id?: number) => useQuery({ queryKey: clavesOportunidades.historial(id??0), queryFn: ({signal}) => solicitarApi<HistorialEtapa[]>(`/opportunities/${id}/stage-history`,{signal}), enabled:id!==undefined });
export const useGuardarOportunidad = (id?: number) => { const cache=useQueryClient(); return useMutation({ mutationFn:(body:SolicitudCrearOportunidad|SolicitudEditarOportunidad)=>solicitarApi<Oportunidad>(id?`/opportunities/${id}`:"/opportunities",{method:id?"PUT":"POST",body}), onSuccess:async(v)=>{await cache.invalidateQueries({queryKey:clavesOportunidades.todas}); if(v.id) await cache.invalidateQueries({queryKey:clavesOportunidades.detalle(v.id)});} }); };
export const useCambiarEtapa = () => { const cache=useQueryClient(); return useMutation({ mutationFn:({id,stageId,note}:{id:number;stageId:number;note?:string})=>solicitarApi<Oportunidad>(`/opportunities/${id}/stage`,{method:"POST",body:{stageId,note}}), onSuccess:async(_,v)=>{ await Promise.all([cache.invalidateQueries({queryKey:clavesOportunidades.todas}),cache.invalidateQueries({queryKey:clavesOportunidades.detalle(v.id)}),cache.invalidateQueries({queryKey:clavesOportunidades.historial(v.id)}),cache.invalidateQueries({queryKey:["actividades"]})]); } }); };
