/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene un usuario del tenant (sólo ADMIN) */
        get: operations["getById"];
        /** Actualiza perfil, rol y estado (sólo ADMIN) */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una oportunidad, con cliente, salón y etapa resueltos (BE-OPP-03) */
        get: operations["getById_1"];
        /** Edita una oportunidad abierta (no cambia etapa, responsable ni estado) */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de un contacto
         * @description Para SELLER exige asignación directa o una oportunidad propia relacionada.
         */
        get: operations["getById_2"];
        /** Edita un contacto */
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de una empresa, con sus contactos (BE-CUS-03)
         * @description Para SELLER exige asignación directa o una oportunidad propia; los contactos anidados también se filtran por ese alcance.
         */
        get: operations["getById_3"];
        /** Edita una empresa */
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuarios del tenant (sólo ADMIN) */
        get: operations["list"];
        put?: never;
        /** Crea un usuario con contraseña temporal (sólo ADMIN) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablece la contraseña temporal e invalida sesiones (sólo ADMIN) */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista oportunidades visibles, paginado
         * @description SELLER ve sólo sus oportunidades; ADMIN y SALES_MANAGER ven todas las del tenant.
         */
        get: operations["list_1"];
        put?: never;
        /** Crea una oportunidad */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia la etapa de una oportunidad abierta y registra el historial (BE-OPP-05) */
        post: operations["changeStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista contactos visibles, paginado
         * @description ADMIN y SALES_MANAGER ven el tenant completo. SELLER ve asignaciones directas y contactos relacionados con oportunidades propias.
         */
        get: operations["list_2"];
        put?: never;
        /** Crea un contacto */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista empresas visibles, paginado
         * @description ADMIN y SALES_MANAGER ven el tenant completo. SELLER ve asignaciones directas y empresas relacionadas con oportunidades propias.
         */
        get: operations["list_3"];
        put?: never;
        /** Crea una empresa */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión y devuelve un JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia la contraseña del usuario autenticado e invalida sus sesiones */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los salones del tenant */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un salón */
        get: operations["getById_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/assignable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista responsables disponibles según el rol actual */
        get: operations["assignable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista las etapas del tenant, ordenadas por posición */
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista orígenes comerciales */
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/stage-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista el historial append-only de etapas en orden cronológico */
        get: operations["stageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista actividades de una oportunidad visible */
        get: operations["byOpportunity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oportunidades visibles agrupadas por etapa, una columna por etapa (BE-OPP-06)
         * @description SELLER ve sólo sus oportunidades; ADMIN y SALES_MANAGER ven todas las del tenant.
         */
        get: operations["board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loss-reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista motivos de pérdida */
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los tipos de evento del tenant */
        get: operations["list_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los servicios adicionales del tenant */
        get: operations["list_9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un servicio adicional */
        get: operations["getById_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista actividades de un contacto visible */
        get: operations["byContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista actividades de una empresa visible */
        get: operations["byCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista tipos de actividad */
        get: operations["list_10"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista actividades visibles, ordenadas y paginadas */
        get: operations["list_11"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "ADMIN" | "SELLER" | "SALES_MANAGER";
            active?: boolean;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            role?: "ADMIN" | "SELLER" | "SALES_MANAGER";
            active?: boolean;
            mustChangePassword?: boolean;
        };
        UpdateOpportunityRequest: {
            title: string;
            /** Format: int64 */
            companyId?: number;
            /** Format: int64 */
            contactId?: number;
            /** Format: int64 */
            venueId: number;
            /** Format: int64 */
            eventTypeId: number;
            estimatedValue?: number;
            /** Format: int32 */
            probability?: number;
            /** Format: date-time */
            eventStart: string;
            /** Format: date-time */
            eventEnd: string;
            /** Format: int32 */
            attendeeCount: number;
            /** Format: date */
            estimatedCloseDate?: string;
            /** Format: int64 */
            originId?: number;
            serviceIds?: number[];
            notes?: string;
        };
        OpportunityResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: int64 */
            companyId?: number;
            /** Format: int64 */
            contactId?: number;
            /** Format: int64 */
            salesRepId?: number;
            /** Format: int64 */
            venueId?: number;
            /** Format: int64 */
            stageId?: number;
            /** Format: int64 */
            eventTypeId?: number;
            /** @enum {string} */
            status?: "ABIERTA" | "GANADA" | "PERDIDA";
            estimatedValue?: number;
            /** Format: date-time */
            eventStart?: string;
            /** Format: date-time */
            eventEnd?: string;
            /** Format: int32 */
            attendeeCount?: number;
            serviceIds?: number[];
            companyName?: string;
            contactName?: string;
            salesRepName?: string;
            venueName?: string;
            stageName?: string;
        };
        ContactRequest: {
            /**
             * Format: int64
             * @description Id de la empresa relacionada. Vacío si es cliente individual (Módulo 1 de la consigna).
             */
            companyId?: number;
            /** @example María */
            firstName: string;
            /** @example Gómez */
            lastName: string;
            /**
             * @description Opcional
             * @example 30123456
             */
            document?: string;
            /**
             * @description Cargo, si corresponde
             * @example Responsable de compras
             */
            position?: string;
            /**
             * Format: email
             * @example maria.gomez@empresa.com
             */
            email?: string;
            /** @example +54 11 4000-0000 */
            phone?: string;
            /** @enum {string} */
            status: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /**
             * Format: int64
             * @description Id del usuario responsable comercial, si ya está asignado
             */
            salesRepId?: number;
            /**
             * Format: int64
             * @description Id del origen comercial
             */
            originId?: number;
            notes?: string;
        };
        ContactResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            companyId?: number;
            companyName?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
        };
        CompanyRequest: {
            /** @example Eventos del Sur SA */
            legalName: string;
            /** @example Eventos del Sur */
            businessName: string;
            /**
             * @description Opcional. Formato: 11 dígitos, con o sin guiones.
             * @example 30-71234567-9
             */
            cuit?: string;
            /** @example Turismo y eventos */
            industry?: string;
            /**
             * Format: email
             * @example contacto@eventosdelsur.com
             */
            email?: string;
            /** @example +54 11 4000-0000 */
            phone?: string;
            /** @example Av. Rivadavia 4500, San Justo */
            address?: string;
            /** @example San Justo */
            locality?: string;
            /** @example https://eventosdelsur.com */
            website?: string;
            /** @enum {string} */
            status: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /**
             * Format: int64
             * @description Id del responsable. Si se omite, el backend aplica la herencia de DP-02
             */
            salesRepId?: number;
            /**
             * Format: int64
             * @description Id del origen comercial
             */
            originId?: number;
            notes?: string;
        };
        CompanyResponse: {
            /** Format: int64 */
            id?: number;
            legalName?: string;
            businessName?: string;
            cuit?: string;
            industry?: string;
            email?: string;
            phone?: string;
            locality?: string;
            /** @enum {string} */
            status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /** Format: int64 */
            salesRepId?: number;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "ADMIN" | "SELLER" | "SALES_MANAGER";
            temporaryPassword?: string;
        };
        ResetPasswordRequest: {
            temporaryPassword?: string;
        };
        CreateOpportunityRequest: {
            /** @example Evento de fin de año - Empresa X */
            title: string;
            /**
             * Format: int64
             * @description Empresa relacionada. Al menos una de companyId/contactId es obligatoria.
             */
            companyId?: number;
            /**
             * Format: int64
             * @description Contacto relacionado. Al menos una de companyId/contactId es obligatoria.
             */
            contactId?: number;
            /**
             * Format: int64
             * @description Usuario responsable comercial (RN-01 de la consigna)
             */
            salesRepId?: number;
            /** Format: int64 */
            venueId: number;
            /**
             * Format: int64
             * @description Etapa inicial — debe ser una etapa abierta (DP-06)
             */
            stageId: number;
            /** Format: int64 */
            eventTypeId: number;
            estimatedValue?: number;
            /** Format: int32 */
            probability?: number;
            /** Format: date-time */
            eventStart: string;
            /** Format: date-time */
            eventEnd: string;
            /** Format: int32 */
            attendeeCount: number;
            /** Format: date */
            estimatedCloseDate?: string;
            /** Format: int64 */
            originId?: number;
            serviceIds?: number[];
            notes?: string;
        };
        ChangeStageRequest: {
            /**
             * Format: int64
             * @description Etapa destino — debe ser una etapa abierta
             */
            stageId: number;
            /** @description Observación opcional sobre el cambio */
            note?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description Email del usuario
             * @example admin@ztech.local
             */
            email: string;
            /**
             * @description Contraseña en texto plano, sólo para este request
             * @example Admin123!
             */
            password: string;
        };
        LoginResponse: {
            /** @description JWT a enviar como 'Authorization: Bearer <token>' en el resto de los requests */
            accessToken?: string;
            /**
             * @description Tipo de token
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description Segundos hasta que el token expira
             * @example 28800
             */
            expiresInSeconds?: number;
            /** @description Indica que sólo se permite cambiar la contraseña antes de continuar */
            mustChangePassword?: boolean;
            /** @description Datos mínimos del usuario autenticado, para que el frontend no tenga que decodificar el JWT */
            user?: components["schemas"]["UserSummary"];
        };
        UserSummary: {
            /** Format: int64 */
            id?: number;
            email?: string;
            firstName?: string;
            lastName?: string;
            role?: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword?: string;
        };
        VenueResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            capacity?: number;
            rate?: number;
            address?: string;
            locality?: string;
            description?: string;
            equipment?: string[];
            /** @enum {string} */
            status?: "DISPONIBLE" | "MANTENIMIENTO" | "INACTIVO";
        };
        PageResponseUserResponse: {
            content?: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        StageResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            position?: number;
            /** @enum {string} */
            kind?: "OPEN" | "WON" | "LOST";
            active?: boolean;
        };
        OriginResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            active?: boolean;
        };
        PageResponseOpportunityResponse: {
            content?: components["schemas"]["OpportunityResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        CompanySummaryResponse: {
            /** Format: int64 */
            id?: number;
            legalName?: string;
            businessName?: string;
            /** Format: int64 */
            salesRepId?: number;
        };
        ContactSummaryResponse: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            email?: string;
            /** @enum {string} */
            status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /** Format: int64 */
            companyId?: number;
            /** Format: int64 */
            salesRepId?: number;
        };
        OpportunityDetailResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            company?: components["schemas"]["CompanySummaryResponse"];
            contact?: components["schemas"]["ContactSummaryResponse"];
            /** Format: int64 */
            salesRepId?: number;
            venue?: components["schemas"]["VenueResponse"];
            stage?: components["schemas"]["StageResponse"];
            /** Format: int64 */
            eventTypeId?: number;
            /** @enum {string} */
            status?: "ABIERTA" | "GANADA" | "PERDIDA";
            estimatedValue?: number;
            finalValue?: number;
            /** Format: int32 */
            probability?: number;
            /** Format: date-time */
            eventStart?: string;
            /** Format: date-time */
            eventEnd?: string;
            /** Format: int32 */
            attendeeCount?: number;
            /** Format: date */
            estimatedCloseDate?: string;
            /** Format: date-time */
            closedAt?: string;
            /** Format: int64 */
            originId?: number;
            /** Format: int64 */
            lossReasonId?: number;
            serviceIds?: number[];
            notes?: string;
        };
        StageHistoryResponse: {
            /** Format: int64 */
            id?: number;
            fromStage?: components["schemas"]["StageResponse"];
            toStage?: components["schemas"]["StageResponse"];
            /** Format: date-time */
            changedAt?: string;
            author?: components["schemas"]["UserSummaryResponse"];
            note?: string;
        };
        UserSummaryResponse: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
        };
        ActivityResponse: {
            /** Format: int64 */
            id?: number;
            type?: components["schemas"]["ActivityTypeResponse"];
            /** Format: date-time */
            occurredAt?: string;
            /** Format: int64 */
            companyId?: number;
            /** Format: int64 */
            contactId?: number;
            /** Format: int64 */
            opportunityId?: number;
            description?: string;
            result?: string;
            author?: components["schemas"]["UserSummaryResponse"];
            /** Format: date-time */
            createdAt?: string;
        };
        ActivityTypeResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            active?: boolean;
        };
        PageResponseActivityResponse: {
            content?: components["schemas"]["ActivityResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        OpportunityBoardResponse: {
            columns?: components["schemas"]["StageColumn"][];
        };
        StageColumn: {
            /** Format: int64 */
            stageId?: number;
            stageName?: string;
            opportunities?: components["schemas"]["OpportunityResponse"][];
        };
        LossReasonResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            active?: boolean;
        };
        EventTypeResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            active?: boolean;
        };
        EventServiceResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            price?: number;
            active?: boolean;
        };
        PageResponseContactResponse: {
            content?: components["schemas"]["ContactResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ContactDetailResponse: {
            /** Format: int64 */
            id?: number;
            company?: components["schemas"]["CompanySummaryResponse"];
            firstName?: string;
            lastName?: string;
            document?: string;
            position?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /** Format: int64 */
            salesRepId?: number;
            /** Format: int64 */
            originId?: number;
            notes?: string;
        };
        PageResponseCompanyResponse: {
            content?: components["schemas"]["CompanyResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        CompanyDetailResponse: {
            /** Format: int64 */
            id?: number;
            legalName?: string;
            businessName?: string;
            cuit?: string;
            industry?: string;
            email?: string;
            phone?: string;
            address?: string;
            locality?: string;
            website?: string;
            /** @enum {string} */
            status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
            /** Format: int64 */
            salesRepId?: number;
            /** Format: int64 */
            originId?: number;
            notes?: string;
            contacts?: components["schemas"]["ContactSummaryResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Usuario inexistente o de otro tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityDetailResponse"];
                };
            };
            /** @description No existe una oportunidad con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityDetailResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Oportunidad actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description No existe una oportunidad con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description La oportunidad está cerrada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactDetailResponse"];
                };
            };
            /** @description No existe un contacto con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactDetailResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Contacto actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
            /** @description No existe un contacto con ese id, o la empresa relacionada no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Ya existe un contacto con ese documento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description No existe una empresa con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDetailResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRequest"];
            };
        };
        responses: {
            /** @description Empresa actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description No existe una empresa con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Ya existe una empresa con ese CUIT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                q?: string;
                role?: "ADMIN" | "SELLER" | "SALES_MANAGER";
                active?: boolean;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserResponse"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                status?: "ABIERTA" | "GANADA" | "PERDIDA";
                stageId?: number;
                originId?: number;
                salesRepId?: number;
                venueId?: number;
                companyId?: number;
                contactId?: number;
                eventFrom?: string;
                eventTo?: string;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseOpportunityResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Oportunidad creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description La empresa, el contacto, el salón o la etapa relacionados no existen */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Falta empresa/contacto, o la etapa inicial no está abierta */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    changeStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStageRequest"];
            };
        };
        responses: {
            /** @description Etapa cambiada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description No existe la oportunidad o la etapa destino */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description La oportunidad está cerrada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Misma etapa, o etapa destino no abierta (usar /win o /lose) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                q?: string;
                status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
                originId?: number;
                salesRepId?: number;
                companyId?: number;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseContactResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Contacto creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
            /** @description La empresa relacionada no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Ya existe un contacto con ese documento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                q?: string;
                status?: "POTENCIAL" | "CLIENTE" | "INACTIVO" | "NO_CONTACTAR";
                originId?: number;
                salesRepId?: number;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCompanyResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRequest"];
            };
        };
        responses: {
            /** @description Empresa creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Ya existe una empresa con ese CUIT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login exitoso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Datos de la solicitud inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Contraseña actualizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La contraseña actual es incorrecta o no cambió */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"][];
                };
            };
        };
    };
    getById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
            /** @description No existe un salón con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    assignable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StageResponse"][];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OriginResponse"][];
                };
            };
        };
    };
    stageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StageHistoryResponse"][];
                };
            };
        };
    };
    byOpportunity: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActivityResponse"];
                };
            };
        };
    };
    board: {
        parameters: {
            query?: {
                q?: string;
                status?: "ABIERTA" | "GANADA" | "PERDIDA";
                stageId?: number;
                originId?: number;
                salesRepId?: number;
                venueId?: number;
                companyId?: number;
                contactId?: number;
                eventFrom?: string;
                eventTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpportunityBoardResponse"];
                };
            };
        };
    };
    list_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LossReasonResponse"][];
                };
            };
        };
    };
    list_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventTypeResponse"][];
                };
            };
        };
    };
    list_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventServiceResponse"][];
                };
            };
        };
    };
    getById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventServiceResponse"];
                };
            };
            /** @description No existe un servicio con ese id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventServiceResponse"];
                };
            };
        };
    };
    byContact: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActivityResponse"];
                };
            };
        };
    };
    byCompany: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActivityResponse"];
                };
            };
        };
    };
    list_10: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityTypeResponse"][];
                };
            };
        };
    };
    list_11: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActivityResponse"];
                };
            };
        };
    };
}
