import { Avatar } from "../../shared/components/Avatar";
import { Boton } from "../../shared/components/Boton";
import { EstadoVacio } from "../../shared/components/EstadoVacio";
import { Icono, type NombreIcono } from "../../shared/components/Icono";
import { desdeHace, fechaHora } from "../../shared/data/formato";
import css from "../../shared/styles/pantalla.module.css";
import type { Actividad } from "./apiActividades";
const icono=(nombre?:string):NombreIcono=>{const n=nombre?.toLowerCase()??"";if(n.includes("llamada"))return"llamada";if(n.includes("correo"))return"email";if(n.includes("mensaje"))return"mensaje";if(n.includes("virtual"))return"virtual";if(n.includes("reunión"))return"reunion";if(n.includes("propuesta"))return"propuesta";return"nota";};
export function LineaDeActividades({actividades,cargando,error,alReintentar}:{actividades:Actividad[];cargando?:boolean;error?:string;alReintentar?:()=>void}){if(cargando)return <EstadoVacio icono="capas" titulo="Cargando actividades…" descripcion="Consultando el historial comercial."/>;if(error)return <EstadoVacio icono="alerta" titulo="No pudimos cargar las actividades" descripcion={error} accion={<Boton variante="secundario" onClick={alReintentar}>Reintentar</Boton>}/>;if(!actividades.length)return <EstadoVacio icono="capas" titulo="Sin actividades registradas" descripcion="Las interacciones realizadas van a aparecer acá."/>;return <ol className={css.linea}>{actividades.map(a=>{const autor=`${a.author?.firstName??""} ${a.author?.lastName??""}`.trim()||"Usuario";return <li key={a.id} className={css.lineaItem}><span className={css.lineaMarca}><Icono nombre={icono(a.type?.name)} tamano={15}/></span><div className={css.lineaCuerpo}><p className={css.lineaTitulo}>{a.type?.name??"Actividad"}<time className={css.lineaFecha} dateTime={a.occurredAt}>{fechaHora(a.occurredAt)} · {desdeHace(a.occurredAt)}</time></p><p className={css.lineaDetalle}>{a.description||"Sin descripción"}{a.result&&<> · {a.result}</>}</p><p className={css.lineaAutor}><Avatar iniciales={autor.split(" ").map(x=>x[0]).join("").slice(0,2)} tamano="sm"/>Registrada por {autor}</p></div></li>})}</ol>}
